### ISSUE TITLE
Builder bug

### ISSUE THREAD

**Issue by ClashingWaves** [Stuxnet-M/Stuxnet-Discord-Grabber#2]
Builder not working corectly. It keeps saying that "line 1 error: import copy unknown command".

**Comment by Stuxnet-M** [comment]
Hey, this could be caused by not having the required packages installed try re-running the setup.bat. If this dosen't work re-install the software with your AV off.

**Comment by ClashingWaves** [comment]
Thank you just running the setup file worked. Looks good mate cheers.

**Comment by Stuxnet-M** [comment]
No problem.
